### ISSUE TITLE
Running relect.kind=external on eclipse fails

### ISSUE THREAD

**Issue by kalhauge** [petablox-project/petablox#11]
Similar to #9, but different error.

```
[Thread-34] ERROR heros.solver.CountingThreadPoolExecutor - Worker thread execution failed: The method does not contain a return statement
Body of method <soot.rtlib.tamiflex.ReflectiveCallsWrapper: void reflectiveCall87(java.lang.Object,java.lang.Object)> does not contain a return statement
        at soot.jimple.validation.ReturnStatementsValidator.validate(ReturnStatementsValidator.java:56)
        at soot.jimple.JimpleBody.validate(JimpleBody.java:125)
        at soot.jimple.JimpleBody.validate(JimpleBody.java:110)
        at soot.baf.BafBody.<init>(BafBody.java:63)
        at soot.baf.Baf.newBody(Baf.java:560)
        at soot.PackManager.convertJimpleBodyToBaf(PackManager.java:1039)
        at soot.PackManager.runBodyPacks(PackManager.java:995)
        at soot.PackManager.access$000(PackManager.java:137)
        at soot.PackManager$1.run(PackManager.java:625)
        at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
        at java.lang.Thread.run(Thread.java:662)
Exception in thread "Thread-34" Body of method <soot.rtlib.tamiflex.ReflectiveCallsWrapper: void reflectiveCall87(java.lang.Object,java.lang.Object)> does not contain a return statement
        at soot.jimple.validation.ReturnStatementsValidator.validate(ReturnStatementsValidator.java:56)
        at soot.jimple.JimpleBody.validate(JimpleBody.java:125)
        at soot.jimple.JimpleBody.validate(JimpleBody.java:110)
        at soot.baf.BafBody.<init>(BafBody.java:63)
        at soot.baf.Baf.newBody(Baf.java:560)
        at soot.PackManager.convertJimpleBodyToBaf(PackManager.java:1039)
        at soot.PackManager.runBodyPacks(PackManager.java:995)
        at soot.PackManager.access$000(PackManager.java:137)
        at soot.PackManager$1.run(PackManager.java:625)
        at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
        at java.lang.Thread.run(Thread.java:662)
Body of method <soot.rtlib.tamiflex.ReflectiveCallsWrapper: void reflectiveCall87(java.lang.Object,java.lang.Object)> does not contain a return statement
        at soot.jimple.validation.ReturnStatementsValidator.validate(ReturnStatementsValidator.java:56)
        at soot.jimple.JimpleBody.validate(JimpleBody.java:125)
        at soot.jimple.JimpleBody.validate(JimpleBody.java:110)
        at soot.baf.BafBody.<init>(BafBody.java:63)
        at soot.baf.Baf.newBody(Baf.java:560)
        at soot.PackManager.convertJimpleBodyToBaf(PackManager.java:1039)
        at soot.PackManager.runBodyPacks(PackManager.java:995)
        at soot.PackManager.access$000(PackManager.java:137)
        at soot.PackManager$1.run(PackManager.java:625)
        at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
        at java.lang.Thread.run(Thread.java:662)
```

Properties file
```
petablox.main.class=org.dacapo.harness.TestHarness
petablox.run.analyses=cipa-0cfa-dlog
petablox.datalox.engine=bddbddb
petablox.err.file=/dev/stderr
petablox.out.file=/dev/stdout

petablox.reflect.kind=external
petablox.run.ids=small,default,large
petablox.args.small=-s small eclipse
petablox.args.default=-s default eclipse
petablox.args.large=-s large eclipse

petablox.class.path=/nix/store/fli0ra2lf8wa7k5dcw6794n8nds7rp03-eclipse-harnessJ6/share/java/commons-logging-1.0.4.jar:/nix/store/fli0ra2lf8wa7k5dcw6794n8nds7rp03-eclipse-harnessJ6/share/java/lucene-demos-2.4.jar:/nix/store/fli0ra2lf8wa7k5dcw6794n8nds7rp03-eclipse-harnessJ6/share/java/eclipse.jar:/nix/store/fli0ra2lf8wa7k5dcw6794n8nds7rp03-eclipse-harnessJ6/share/java/lucene-core-2.4.jar:/nix/store/fli0ra2lf8wa7k5dcw6794n8nds7rp03-eclipse-harnessJ6/share/java/jython.jar:/nix/store/fli0ra2lf8wa7k5dcw6794n8nds7rp03-eclipse-harnessJ6/share/java/commons-daemon.jar:/nix/store/fli0ra2lf8wa7k5dcw6794n8nds7rp03-eclipse-harnessJ6/share/java/serializer.jar:/nix/store/fli0ra2lf8wa7k5dcw6794n8nds7rp03-eclipse-harnessJ6/share/java/tpcc.jar:/nix/store/fli0ra2lf8wa7k5dcw6794n8nds7rp03-eclipse-harnessJ6/share/java/h2-1.2.121.jar:/nix/store/fli0ra2lf8wa7k5dcw6794n8nds7rp03-eclipse-harnessJ6/share/java/xalan-benchmark.jar:/nix/store/fli0ra2lf8wa7k5dcw6794n8nds7rp03-eclipse-harnessJ6/share/java/pmd-4.2.5.jar:/nix/store/fli0ra2lf8wa7k5dcw6794n8nds7rp03-eclipse-harnessJ6/share/java/xml-apis-ext.jar:/nix/store/fli0ra2lf8wa7k5dcw6794n8nds7rp03-eclipse-harnessJ6/share/java/crimson-1.1.3.jar:/nix/store/fli0ra2lf8wa7k5dcw6794n8nds7rp03-eclipse-harnessJ6/share/java/fop.jar:/nix/store/fli0ra2lf8wa7k5dcw6794n8nds7rp03-eclipse-harnessJ6/share/java/janino-2.5.12.jar:/nix/store/fli0ra2lf8wa7k5dcw6794n8nds7rp03-eclipse-harnessJ6/share/java/constantine-0.4.jar:/nix/store/fli0ra2lf8wa7k5dcw6794n8nds7rp03-eclipse-harnessJ6/share/java/derbyclient.jar:/nix/store/fli0ra2lf8wa7k5dcw6794n8nds7rp03-eclipse-harnessJ6/share/java/xalan.jar:/nix/store/fli0ra2lf8wa7k5dcw6794n8nds7rp03-eclipse-harnessJ6/share/java/avrora-cvs-20091224.jar:/nix/store/fli0ra2lf8wa7k5dcw6794n8nds7rp03-eclipse-harnessJ6/share/java/batik-all-1.7.jar:/nix/store/fli0ra2lf8wa7k5dcw6794n8nds7rp03-eclipse-harnessJ6/share/java/avalon-framework-4.2.0.jar:/nix/store/fli0ra2lf8wa7k5dcw6794n8nds7rp03-eclipse-harnessJ6/share/java/commons-codec.jar:/nix/store/fli0ra2lf8wa7k5dcw6794n8nds7rp03-eclipse-harnessJ6/share/java/asm-3.1.jar:/nix/store/fli0ra2lf8wa7k5dcw6794n8nds7rp03-eclipse-harnessJ6/share/java/jna-posix.jar:/nix/store/fli0ra2lf8wa7k5dcw6794n8nds7rp03-eclipse-harnessJ6/share/java/derbynet.jar:/nix/store/fli0ra2lf8wa7k5dcw6794n8nds7rp03-eclipse-harnessJ6/share/java/jaxen-1.1.1.jar:/nix/store/fli0ra2lf8wa7k5dcw6794n8nds7rp03-eclipse-harnessJ6/share/java/xercesImpl.jar:/nix/store/fli0ra2lf8wa7k5dcw6794n8nds7rp03-eclipse-harnessJ6/share/java/luindex.jar:/nix/store/fli0ra2lf8wa7k5dcw6794n8nds7rp03-eclipse-harnessJ6/share/java/xmlgraphics-commons-1.3.1.jar:/nix/store/fli0ra2lf8wa7k5dcw6794n8nds7rp03-eclipse-harnessJ6/share/java/commons-logging.jar:/nix/store/fli0ra2lf8wa7k5dcw6794n8nds7rp03-eclipse-harnessJ6/share/java/derbytools.jar:/nix/store/fli0ra2lf8wa7k5dcw6794n8nds7rp03-eclipse-harnessJ6/share/java/daytrader.jar:/nix/store/fli0ra2lf8wa7k5dcw6794n8nds7rp03-eclipse-harnessJ6/share/java/batik-all.jar:/nix/store/fli0ra2lf8wa7k5dcw6794n8nds7rp03-eclipse-harnessJ6/share/java/commons-httpclient.jar:/nix/store/fli0ra2lf8wa7k5dcw6794n8nds7rp03-eclipse-harnessJ6/share/java/dacapo-tomcat.jar:/nix/store/fli0ra2lf8wa7k5dcw6794n8nds7rp03-eclipse-harnessJ6/share/java/bootstrap.jar:/nix/store/fli0ra2lf8wa7k5dcw6794n8nds7rp03-eclipse-harnessJ6/share/java/jna.jar:/nix/store/fli0ra2lf8wa7k5dcw6794n8nds7rp03-eclipse-harnessJ6/share/java/xalan-2.6.0.jar:/nix/store/fli0ra2lf8wa7k5dcw6794n8nds7rp03-eclipse-harnessJ6/share/java/xml-apis.jar:/nix/store/fli0ra2lf8wa7k5dcw6794n8nds7rp03-eclipse-harnessJ6/share/java/tomcat-juli.jar:/nix/store/fli0ra2lf8wa7k5dcw6794n8nds7rp03-eclipse-harnessJ6/share/java/junit-3.8.1.jar:/nix/store/fli0ra2lf8wa7k5dcw6794n8nds7rp03-eclipse-harnessJ6/share/java/antlr-3.1.3.jar:/nix/store/fli0ra2lf8wa7k5dcw6794n8nds7rp03-eclipse-harnessJ6/share/java/lusearch.jar:/nix/store/fli0ra2lf8wa7k5dcw6794n8nds7rp03-eclipse-harnessJ6/share/java/derby.jar:/nix/store/fli0ra2lf8wa7k5dcw6794n8nds7rp03-eclipse-harnessJ6/share/java/serializer-2.7.0.jar:/nix/store/fli0ra2lf8wa7k5dcw6794n8nds7rp03-eclipse-harnessJ6/share/java/xerces_2_5_0.jar:/nix/store/fli0ra2lf8wa7k5dcw6794n8nds7rp03-eclipse-harnessJ6/share/java/sunflow-0.07.2.jar:/nix/store/fli0ra2lf8wa7k5dcw6794n8nds7rp03-eclipse-harnessJ6/share/java/dacapo-9.12-bach.jar:/nix/store/fli0ra2lf8wa7k5dcw6794n8nds7rp03-eclipse-harnessJ6/share/java/derbyTesting.jar:/nix/store/fli0ra2lf8wa7k5dcw6794n8nds7rp03-eclipse-harnessJ6/share/java/commons-io-1.3.1.jar:/nix/store/fli0ra2lf8wa7k5dcw6794n8nds7rp03-eclipse-harnessJ6/share/java/asm-commons-3.1.jar
```

**Comment by kalhauge** [comment]
Also working in f8c55cc6fa140eeae9d7cfbb9b5cb88f87bbc78a.
