### ISSUE TITLE
Deadlock analysis does not work

### ISSUE THREAD

**Issue by kalhauge** [petablox-project/petablox#14]
Deadlock analysis does not seem to work. 

Steps to recreate in JBX:

```
./jbx petablox -a deadlock-java sunflow
```

```
java.lang.Error: ERROR: ClassicProject: Task named 'deadlock-java' not found in project.
        at petablox.project.Messages.fatal(Messages.java:24)
        at petablox.project.ClassicProject.getTask(ClassicProject.java:355)
        at petablox.project.ClassicProject.runTask(ClassicProject.java:424)
        at petablox.project.ClassicProject.run(ClassicProject.java:118)
        at petablox.project.Main.run(Main.java:78)
        at petablox.project.Main.main(Main.java:50)
```

**Comment by rmmilewi** [comment]
I second this issue. In the analysis directory, I found that the the deadlock directory was missing completely. I'm sure it's possible to port over the analysis from Chord, but I'm not sure how much work that would entail.

**Comment by mayurnaik** [comment]
We are working on it, and plan to have it ready soon (in a matter of weeks).

-- Mayur

**Comment by rmmilewi** [comment]
Oh, fantastic! I can't wait to switch out Chord with Petablox in my experimental toolchain.

Thanks for the speedy reply!
