### ISSUE TITLE
How to run analysis using LogicBlox as Datalog engine, instead of bddbddb ?

### ISSUE THREAD

**Issue by rayobanon** [petablox-project/petablox#24]
I try to run the following command,
ant -Dpetablox.datalog.engine=LOGICBLOX4 -Dpetablox.work.dir=examples/custom_world/ -Dpetablox.ctxt.kind='co' -Dpetablox.run.analyses=ctxts-java,argCopy-dlog,cspa-kobj-dlog,downcast-dlog run

But I get an error,

Petablox run initiated at: Jul 30, 2018 11:21:27 PM
Warning: java.lang.invoke.LambdaMetafactory is a phantom class!
NUMBER OF CLASSES IN SCENE: 2809
Starting command: 'lb create --overwrite petablox:dsFcXMpuxdxYfBlghmevfpBm'
java.lang.Error: Command 'lb create --overwrite petablox:dsFcXMpuxdxYfBlghmevfpBm' terminated abnormally: Cannot run program "lb": error=2, No such file or directory
	at petablox.project.Messages.fatal(Messages.java:24)
	at petablox.project.OutDirUtils.executeCaptureWithFailOnError(OutDirUtils.java:153)
	at petablox.logicblox.LogicBloxUtils.initializeWorkspace(LogicBloxUtils.java:162)
	at petablox.project.ClassicProject.build(ClassicProject.java:80)
	at petablox.project.ClassicProject.getTask(ClassicProject.java:373)
	at petablox.project.ClassicProject.runTask(ClassicProject.java:456)
	at petablox.project.ClassicProject.run(ClassicProject.java:131)
	at petablox.project.Main.run(Main.java:88)
	at petablox.project.Main.main(Main.java:56)

I would like to know if it is the correct way to use LogicBlox as datalog engine, or other petablox properties need to be set?

**Comment by KihongHeo** [comment]
Hi. Thanks for your interest. 
Sorry but we stopped supporting LogicBlox and plan to replace it with [Souffle](https://github.com/souffle-lang) soon. Please try bddbddb until we complete that.
