### ISSUE TITLE
Petablox fails to work with cicg2dot

### ISSUE THREAD

**Issue by kalhauge** [petablox-project/petablox#3]
Petablox 0.1 fails to work on logicblox 4:

```
Failed process standard output:
block PM: line 1: error: predicate 'P' is not declared at level 0 (code: PREDICATE_UNDECLARED)
    PM(d0,d1) -> P(d0),M(d1).
    
                 ^^^^^

Backtrace: 
  2 BloxDataException::backtrace()
  3 BloxDataException::BloxDataException(std::string const&, bool)
  4 connectivity::runCommand(Ptr<connectivity::DatabaseInterface>, connectivity::CommandContainer&)
  5 connectivity::ConnectivityCommands::run(Ptr<connectivity::DatabaseInterface>)
  6 connectivity::BranchWorkQueue::workerThreadMain(int, Ptr<Future<unit_t>::ResultBox>, environment::StandardEnvironment::thread_env_t)
  7 boost::detail::thread_data<boost::_bi::bind_t<void, boost::_mfi::mf3<void, connectivity::BranchWorkQueue, int, Ptr<Future<unit_t>::ResultBox>, environment::StandardEnvironment::thread_env_t>, boost::_bi::list4<boost::_bi::value<connectivity::BranchWorkQueue*>, boost::_bi::value<int>, boost::_bi::value<Ptr<Future<unit_t>::ResultBox> >, boost::_bi::value<environment::StandardEnvironment::thread_env_t> > > >::run()
  8 
  9 
 10 clone


java.lang.Error: Command 'lb addblock --file /nix/store/ydvgf9c2r3s39jngfjqj728lpcjzy8sg-petablox-lb-4.2.0-cicg-avroraJ7/sandbox/chord_output/logicblox/PM.type chord:pFIjico9Lb9kfkejFLiiafcM' terminated abnormally: Process failed with retcode=1
	at petablox.project.Messages.fatal(Messages.java:24)
	at petablox.project.OutDirUtils.executeCaptureWithFailOnError(OutDirUtils.java:147)
	at petablox.logicblox.LogicBloxUtils.addBlock(LogicBloxUtils.java:85)
	at petablox.logicblox.LogicBloxUtils.addBlock(LogicBloxUtils.java:78)
	at petablox.logicblox.LogicBloxExporter.saveRelation(LogicBloxExporter.java:70)
	at petablox.bddbddb.Rel.saveToLogicBlox(Rel.java:341)
	at petablox.project.analyses.ProgramRel.save(ProgramRel.java:85)
	at petablox.project.analyses.ProgramRel.run(ProgramRel.java:39)
	at petablox.util.soot.SootUtilities.getMethod(SootUtilities.java:58)
	at petablox.analyses.point.DomP.toUniqueString(DomP.java:56)
	at petablox.analyses.point.DomP.toUniqueString(DomP.java:30)
	at petablox.bddbddb.Dom.toUniqueString(Dom.java:95)
	at petablox.logicblox.LogicBloxExporter.saveDomainData(LogicBloxExporter.java:88)
	at petablox.logicblox.LogicBloxExporter.saveDomain(LogicBloxExporter.java:42)
	at petablox.bddbddb.Dom.saveToLogicBlox(Dom.java:86)
	at petablox.project.analyses.ProgramDom.save(ProgramDom.java:64)
	at petablox.project.analyses.ProgramDom.run(ProgramDom.java:44)
	at petablox.project.ClassicProject.runTask(ClassicProject.java:404)
	at petablox.project.ClassicProject.runTask(ClassicProject.java:401)
	at petablox.project.ClassicProject.runTask(ClassicProject.java:401)
	at petablox.project.ClassicProject.runTask(ClassicProject.java:401)
	at petablox.project.ClassicProject.runTask(ClassicProject.java:401)
	at petablox.project.ClassicProject.runTask(ClassicProject.java:425)
	at petablox.analyses.alias.CICG2DotGraphAnalysis.run(CICG2DotGraphAnalysis.java:27)
	at petablox.project.ClassicProject.runTask(ClassicProject.java:404)
	at petablox.project.ClassicProject.runTask(ClassicProject.java:425)
	at petablox.project.ClassicProject.run(ClassicProject.java:118)
	at petablox.project.Main.run(Main.java:78)
	at petablox.project.Main.main(Main.java:50)
```

Chord.properties:
```
chord.main.class=avrora.Main
chord.run.analyses=cicg2dot-java
chord.datalog.engine=logicblox4
chord.err.file=/dev/stderr
chord.out.file=/dev/stdout

chord.class.path=/nix/store/7nfc18s0wkyz5wax96aw4nnw454irplm-avroraJ7/share/java/avrora-beta-1.7.110.jar
```

**Comment by kalhauge** [comment]
Upgraded to version v1.0: 

That might have fixed the problem. Because I'm getting a new set of problems.

```
Redirecting stdout to file: /dev/stdout
Redirecting stderr to file: /dev/stderr
Petablox run initiated at: Jan 18, 2016 12:56:26 AM
Warning: java.lang.invoke.LambdaMetafactory is a phantom class!
NUMBER OF CLASSES IN SCENE: 3943
Starting command: 'lb create --overwrite petablox:FEiMXo-bjzpVakp1e1hcvh'
Finished command: 'lb create --overwrite petablox:FEiMXo-bjzpVakp1e1hcvh'
LogicBlox workspace initialized: petablox:FEiMXo-bjzpVakp1e1hcvh
OPT config = data.config
ERROR: TrgtParser: Type of target 'AllowH' unknown.
ERROR: TrgtParser: Type of target 'roots' unknown.
ERROR: TrgtParser: Type of target 'initCOC' unknown.
ERROR: TrgtParser: Type of target 'DenyO' unknown.
ERROR: TrgtParser: Type of target 'DenyH' unknown.
ERROR: TrgtParser: Type of target 'DenyI' unknown.
ERROR: TrgtParser: Type of target 'AllowO' unknown.
ERROR: TrgtParser: Type of target 'AllowI' unknown.
ERROR: TrgtParser: Type of target 'gen' unknown.
ERROR: TrgtParser: Type of target 'CL' unknown.
ERROR: TrgtParser: Type of target 'initCHC' unknown.
ERROR: TrgtParser: Type of target 'OK' unknown.
ERROR: TrgtParser: Type of target 'truncCKC' unknown.
ERROR: TrgtParser: Type of target 'HK' unknown.
ERROR: TrgtParser: Type of target 'kill' unknown.
ERROR: TrgtParser: Type of target 'IK' unknown.
ERROR: TrgtParser: Type of target 'contain' unknown.
ERROR: TrgtParser: Type of target 'allow' unknown.
ERROR: TrgtParser: Type of target 'initCIC' unknown.
```

```
petablox.main.class=avrora.Main
petablox.run.analyses=cicg2dot-java
petablox.datalog.engine=logicblox4
petablox.err.file=/dev/stderr
petablox.out.file=/dev/stdout

petablox.class.path=/nix/store/7nfc18s0wkyz5wax96aw4nnw454irplm-avroraJ7/share/java/avrora-beta-1.7.110.jar
```

**Comment by akamath32** [comment]
Hi,

Can you please try running the same test case but instead making the following change:
    
    petablox.run.analyses=cicg2dot-java

to

    petablox.run.analyses=cipa-0cfa-dlog,cicg2dot-java


The error you are receiving is because you haven't run the pointer analyses to generate the call graph which ``cicg2dot-java`` can dump. 
We will need to automate this dependency or give a better error message.

**Comment by kalhauge** [comment]
Tried, same results. 

Running with bddbdd yields fine results.

**Comment by kalhauge** [comment]
Even running with `petablox.run.analyses=cipa-0cfa-dlog,cicg2dot-java` alone yields the same results.

**Comment by kalhauge** [comment]
A total execution here [avrora.tar.gz](https://github.com/petablox-project/petablox/files/93716/avrora.tar.gz)

**Comment by akamath32** [comment]
Thanks, will look into this right away.

**Comment by akamath32** [comment]
Can you please pull the latest gt-develop branch and try out your use case.
If it's fine, we can merge it over in a point release.

**Comment by kalhauge** [comment]
That worked! Great Job,

 I have created a small pull request, that if you accept will improve our workflow.

**Comment by akamath32** [comment]
Hi Christian,

I agree that would make a good workflow in changing the links to HTTPS instead of SSH.
I will merge that pull request in.

Thanks
Aditya Kamath
Graduate Student
Computer Science
Georgia Institute of Technology

On 19-Jan-2016, at 5:40 PM, Christian Kalhauge <notifications@github.com<mailto:notifications@github.com>> wrote:


That worked! Great Job,

I have created a small pull request, that if you accept will improve our workflow.
