### ISSUE TITLE
Soot exception when analyzing Jython

### ISSUE THREAD

**Issue by joecox** [petablox-project/petablox#6]
When running the cicg2dot-java callgraph analysis with Logicblox, we get the following error from Soot:

```
Exception in thread "main" soot.ResolutionFailedException:
Resolved <org.python.modules.zipimport.zipimporter: org.python.core.PyString __doc__> to 
<org.python.modules.zipimport.zipimporter: org.python.core.PyString __doc__> which has wrong static-ness
        at soot.AbstractSootFieldRef.checkStatic(AbstractSootFieldRef.java:87)
        at soot.AbstractSootFieldRef.resolve(AbstractSootFieldRef.java:102)
        at soot.AbstractSootFieldRef.resolve(AbstractSootFieldRef.java:81)
        at soot.jimple.internal.AbstractInstanceFieldRef.getField(AbstractInstanceFieldRef.java:93)
        at petablox.util.soot.SootUtilities.isStaticGet(SootUtilities.java:97)
        at petablox.program.RTA.processMethod(RTA.java:444)
        at petablox.program.RTA.build(RTA.java:229)
        at petablox.program.RTA.getMethods(RTA.java:130)
        at petablox.program.Program.buildMethods(Program.java:208)
        at petablox.program.Program.buildClasses(Program.java:263)
        at petablox.program.Program.getTypes(Program.java:657)
        at petablox.analyses.type.DomT.fill(DomT.java:26)
        at petablox.project.analyses.ProgramDom.run(ProgramDom.java:38)
        at petablox.project.ClassicProject.runTask(ClassicProject.java:404)
        at petablox.project.ClassicProject.runTask(ClassicProject.java:401)
        at petablox.project.ClassicProject.runTask(ClassicProject.java:401)
        at petablox.project.ClassicProject.runTask(ClassicProject.java:425)
        at petablox.analyses.alias.CICG2DotGraphAnalysis.run(CICG2DotGraphAnalysis.java:27)
        at petablox.project.ClassicProject.runTask(ClassicProject.java:404)
        at petablox.project.ClassicProject.runTask(ClassicProject.java:425)
        at petablox.project.ClassicProject.run(ClassicProject.java:118)
        at petablox.project.Main.run(Main.java:78)
        at petablox.project.Main.main(Main.java:50)
```

We got this error from Soot a while ago when running with the old Doop framework and our fix was to use one of their phase options.  [This link][soot_options] details that in the `jb.tr` phase, you can set the `ignore-wrong-staticness` option to `true`, which will silence the error.  (Using this approach assumes that we trust Jython to be correct over Soot, not the other way around).

If possible, we'd like to have an option we can pass to Petablox that will enable this option for Soot.

[soot_options]: https://ssebuild.cased.de/nightly/soot/doc/soot_options.htm

**Comment by sulekhark** [comment]
Hi Joe,

Could you please try the following:

Add the following line in src/petablox/Program.java, in the constructor (after line 112) 
PhaseOptions.v().setPhaseOption("jb.tr", "ignore-wrong-staticness:true");

We do not currently have a system to pass soot options to petablox. We can discuss this later.

**Comment by joecox** [comment]
Thanks Sulekha.  I'll try that, and open a pull request so we have some code for a later discussion.
