### ISSUE TITLE
Running reflect.kind=external on pmd fails

### ISSUE THREAD

**Issue by kalhauge** [petablox-project/petablox#9]
Running on external reflection handling on pmd fails. 

Recreate the error using JBX:
```
./jbx petablox -e null -a cipa-0cfa-dlog -r external  pmd-harness --java 6
```

```
java.lang.RuntimeException: Failed to convert <org.objectweb.asm.ClassReader: int readField(org.objectweb.asm.ClassVisitor,org.objectweb.asm.Context,int)>
        at soot.asm.AsmMethodSource.getBody(AsmMethodSource.java:1776)
        at soot.SootMethod.getBodyFromMethodSource(SootMethod.java:91)
        at soot.SootMethod.retrieveActiveBody(SootMethod.java:322)
        at soot.jimple.toolkits.annotation.LineNumberAdder.internalTransform(LineNumberAdder.java:44)
        at soot.PackManager.runPacksNormally(PackManager.java:457)
        at soot.PackManager.runPacks(PackManager.java:396)
        at soot.Main.run(Main.java:271)
        at soot.Main.main(Main.java:147)
        at de.bodden.tamiflex.booster.ReflInliner.main(ReflInliner.java:67)
Caused by: java.lang.RuntimeException: Trying to create virtual invoke expression for interface type (org.objectweb.asm.FieldVisitor in file null). Use JInterfaceInvokeExp
r instead!
        at soot.jimple.internal.JVirtualInvokeExpr.<init>(JVirtualInvokeExpr.java:48)
        at soot.jimple.Jimple.newVirtualInvokeExpr(Jimple.java:419)
        at soot.asm.AsmMethodSource.convertMethodInsn(AsmMethodSource.java:1177)
        at soot.asm.AsmMethodSource.convert(AsmMethodSource.java:1607)
        at soot.asm.AsmMethodSource.getBody(AsmMethodSource.java:1774)
        ... 8 more
```

```
petablox.main.class=org.dacapo.harness.TestHarness
petablox.run.analyses=cipa-0cfa-dlog
petablox.datalox.engine=bddbddb
petablox.err.file=/dev/stderr
petablox.out.file=/dev/stdout

petablox.reflect.kind=external
petablox.run.ids=xsmall,small,default,large
petablox.args.xsmall=-s xsmall pmd
petablox.args.small=-s small pmd
petablox.args.default=-s default pmd
petablox.args.large=-s large pmd

petablox.class.path=/nix/store/3rbxmyns2lvdwpsvv6y227qlgn21lpiy-pmd-harnessJ6/share/java/xercesImpl.jar:/nix/store/3rbxmyns2lvdwpsvv6y227qlgn21lpiy-pmd-harnessJ6/share/java/asm-commons-3.1.jar:/nix/store/3rbxmyns2lvdwpsvv6y227qlgn21lpiy-pmd-harnessJ6/share/java/serializer-2.7.0.jar:/nix/store/3rbxmyns2lvdwpsvv6y227qlgn21lpiy-pmd-harnessJ6/share/java/lusearch.jar:/nix/store/3rbxmyns2lvdwpsvv6y227qlgn21lpiy-pmd-harnessJ6/share/java/xerces_2_5_0.jar:/nix/store/3rbxmyns2lvdwpsvv6y227qlgn21lpiy-pmd-harnessJ6/share/java/xalan.jar:/nix/store/3rbxmyns2lvdwpsvv6y227qlgn21lpiy-pmd-harnessJ6/share/java/commons-httpclient.jar:/nix/store/3rbxmyns2lvdwpsvv6y227qlgn21lpiy-pmd-harnessJ6/share/java/jna-posix.jar:/nix/store/3rbxmyns2lvdwpsvv6y227qlgn21lpiy-pmd-harnessJ6/share/java/derbyTesting.jar:/nix/store/3rbxmyns2lvdwpsvv6y227qlgn21lpiy-pmd-harnessJ6/share/java/dacapo-9.12-bach.jar:/nix/store/3rbxmyns2lvdwpsvv6y227qlgn21lpiy-pmd-harnessJ6/share/java/commons-io-1.3.1.jar:/nix/store/3rbxmyns2lvdwpsvv6y227qlgn21lpiy-pmd-harnessJ6/share/java/dacapo-tomcat.jar:/nix/store/3rbxmyns2lvdwpsvv6y227qlgn21lpiy-pmd-harnessJ6/share/java/derbyclient.jar:/nix/store/3rbxmyns2lvdwpsvv6y227qlgn21lpiy-pmd-harnessJ6/share/java/h2-1.2.121.jar:/nix/store/3rbxmyns2lvdwpsvv6y227qlgn21lpiy-pmd-harnessJ6/share/java/jython.jar:/nix/store/3rbxmyns2lvdwpsvv6y227qlgn21lpiy-pmd-harnessJ6/share/java/pmd-4.2.5.jar:/nix/store/3rbxmyns2lvdwpsvv6y227qlgn21lpiy-pmd-harnessJ6/share/java/serializer.jar:/nix/store/3rbxmyns2lvdwpsvv6y227qlgn21lpiy-pmd-harnessJ6/share/java/xml-apis.jar:/nix/store/3rbxmyns2lvdwpsvv6y227qlgn21lpiy-pmd-harnessJ6/share/java/sunflow-0.07.2.jar:/nix/store/3rbxmyns2lvdwpsvv6y227qlgn21lpiy-pmd-harnessJ6/share/java/commons-logging.jar:/nix/store/3rbxmyns2lvdwpsvv6y227qlgn21lpiy-pmd-harnessJ6/share/java/fop.jar:/nix/store/3rbxmyns2lvdwpsvv6y227qlgn21lpiy-pmd-harnessJ6/share/java/jaxen-1.1.1.jar:/nix/store/3rbxmyns2lvdwpsvv6y227qlgn21lpiy-pmd-harnessJ6/share/java/avalon-framework-4.2.0.jar:/nix/store/3rbxmyns2lvdwpsvv6y227qlgn21lpiy-pmd-harnessJ6/share/java/derby.jar:/nix/store/3rbxmyns2lvdwpsvv6y227qlgn21lpiy-pmd-harnessJ6/share/java/commons-daemon.jar:/nix/store/3rbxmyns2lvdwpsvv6y227qlgn21lpiy-pmd-harnessJ6/share/java/luindex.jar:/nix/store/3rbxmyns2lvdwpsvv6y227qlgn21lpiy-pmd-harnessJ6/share/java/janino-2.5.12.jar:/nix/store/3rbxmyns2lvdwpsvv6y227qlgn21lpiy-pmd-harnessJ6/share/java/asm-3.1.jar:/nix/store/3rbxmyns2lvdwpsvv6y227qlgn21lpiy-pmd-harnessJ6/share/java/derbynet.jar:/nix/store/3rbxmyns2lvdwpsvv6y227qlgn21lpiy-pmd-harnessJ6/share/java/avrora-cvs-20091224.jar:/nix/store/3rbxmyns2lvdwpsvv6y227qlgn21lpiy-pmd-harnessJ6/share/java/batik-all-1.7.jar:/nix/store/3rbxmyns2lvdwpsvv6y227qlgn21lpiy-pmd-harnessJ6/share/java/commons-codec.jar:/nix/store/3rbxmyns2lvdwpsvv6y227qlgn21lpiy-pmd-harnessJ6/share/java/xalan-2.6.0.jar:/nix/store/3rbxmyns2lvdwpsvv6y227qlgn21lpiy-pmd-harnessJ6/share/java/constantine-0.4.jar:/nix/store/3rbxmyns2lvdwpsvv6y227qlgn21lpiy-pmd-harnessJ6/share/java/junit-3.8.1.jar:/nix/store/3rbxmyns2lvdwpsvv6y227qlgn21lpiy-pmd-harnessJ6/share/java/commons-logging-1.0.4.jar:/nix/store/3rbxmyns2lvdwpsvv6y227qlgn21lpiy-pmd-harnessJ6/share/java/tomcat-juli.jar:/nix/store/3rbxmyns2lvdwpsvv6y227qlgn21lpiy-pmd-harnessJ6/share/java/antlr-3.1.3.jar:/nix/store/3rbxmyns2lvdwpsvv6y227qlgn21lpiy-pmd-harnessJ6/share/java/lucene-demos-2.4.jar:/nix/store/3rbxmyns2lvdwpsvv6y227qlgn21lpiy-pmd-harnessJ6/share/java/daytrader.jar:/nix/store/3rbxmyns2lvdwpsvv6y227qlgn21lpiy-pmd-harnessJ6/share/java/batik-all.jar:/nix/store/3rbxmyns2lvdwpsvv6y227qlgn21lpiy-pmd-harnessJ6/share/java/xalan-benchmark.jar:/nix/store/3rbxmyns2lvdwpsvv6y227qlgn21lpiy-pmd-harnessJ6/share/java/xmlgraphics-commons-1.3.1.jar:/nix/store/3rbxmyns2lvdwpsvv6y227qlgn21lpiy-pmd-harnessJ6/share/java/bootstrap.jar:/nix/store/3rbxmyns2lvdwpsvv6y227qlgn21lpiy-pmd-harnessJ6/share/java/eclipse.jar:/nix/store/3rbxmyns2lvdwpsvv6y227qlgn21lpiy-pmd-harnessJ6/share/java/lucene-core-2.4.jar:/nix/store/3rbxmyns2lvdwpsvv6y227qlgn21lpiy-pmd-harnessJ6/share/java/jna.jar:/nix/store/3rbxmyns2lvdwpsvv6y227qlgn21lpiy-pmd-harnessJ6/share/java/crimson-1.1.3.jar:/nix/store/3rbxmyns2lvdwpsvv6y227qlgn21lpiy-pmd-harnessJ6/share/java/tpcc.jar:/nix/store/3rbxmyns2lvdwpsvv6y227qlgn21lpiy-pmd-harnessJ6/share/java/derbytools.jar:/nix/store/3rbxmyns2lvdwpsvv6y227qlgn21lpiy-pmd-harnessJ6/share/java/xml-apis-ext.jar
```

**Comment by sulekhark** [comment]
Here's why the crash is happening:

- pmd uses asm-3.1.jar which contains package org.objectweb.asm
- Since petablox uses soot which in turn uses asm-debug-all-5.0.3.jar, petablox.jar contains org.objectweb.asm
- Now, in the dynamic analysis run of pmd, petablox.jar is passed as an argument to  -Xbootclasspath/p. Because of this, classes from package org.objectweb.asm are picked up from petablox.jar instead of pmd-specific classpaths. They are incompatible and hence the crash. (chord.jar did not have this package and therefore, it worked fine with old chord)

This behavior can be verified by passing -verbose:class option to jvm.

**Comment by kalhauge** [comment]
Ok, so the solution is to change to the dynamic reflection handling (which currently doesn't work on the full dacapo jar, #8).

**Comment by sulekhark** [comment]
No, this problem will occur with both "dynamic" and "external" reflection handling. This happens because petablox executes pmd (in both reflection handling mechanisms) to find out reflective calls. During this execution, those specific class files required by pmd are loaded from a different location.

**Comment by kalhauge** [comment]
Do you have a planned solution? Maybe separating the java classpath and the petablox classpath?

**Comment by sulekhark** [comment]
Yes, something like that needs to be done.

**Comment by kalhauge** [comment]
Jython seems to have a similar issue: 

````
java.lang.RuntimeException: Failed to convert <org.python.compiler.ClassFile: void endFields()>
        at soot.asm.AsmMethodSource.getBody(AsmMethodSource.java:1776)
        at soot.SootMethod.getBodyFromMethodSource(SootMethod.java:91)
        at soot.SootMethod.retrieveActiveBody(SootMethod.java:322)
        at soot.jimple.toolkits.annotation.LineNumberAdder.internalTransform(LineNumberAdder.java:44)
        at soot.PackManager.runPacksNormally(PackManager.java:457)
        at soot.PackManager.runPacks(PackManager.java:396)
        at soot.Main.run(Main.java:271)
        at soot.Main.main(Main.java:147)
        at de.bodden.tamiflex.booster.ReflInliner.main(ReflInliner.java:67)
Caused by: java.lang.RuntimeException: Trying to create interface invoke expression for non-interface type: org.objectweb.asm.FieldVisitor Use JVirtualInvokeExpr or JSpecialInvokeExpr instead!
        at soot.jimple.internal.JInterfaceInvokeExpr.<init>(JInterfaceInvokeExpr.java:50)
        at soot.jimple.Jimple.newInterfaceInvokeExpr(Jimple.java:446)
        at soot.asm.AsmMethodSource.convertMethodInsn(AsmMethodSource.java:1179)
        at soot.asm.AsmMethodSource.convert(AsmMethodSource.java:1607)
        at soot.asm.AsmMethodSource.getBody(AsmMethodSource.java:1774)
        ... 8 more
```

**Comment by kalhauge** [comment]
On the newest version of master this works. (f8c55cc6fa140eeae9d7cfbb9b5cb88f87bbc78a)
